# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: drone-add-cron
#   namespace: devops
#   labels:
#     app: drone-add-cron
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: drone-add-cron
#   template:
#     metadata:
#       labels:
#         app: drone-add-cron
#     spec:
#       containers:
#         - name: drone-add-cron
#           image: "harbor.k8s.lan/k8s/drone-cli:latest"
#           imagePullPolicy: Always
#           resources: {}
#           command: ["/bin/sh", "-c"]
#           args:
#             # [
#             #   "until curl -s ${DRONE_SERVER}/healthz | grep -q 'OK'; do echo 'Waiting for Drone server...' && sleep 2; done; for r in ${REPOS}; do drone cron add --branch main theautomation/${r} saturday '0 1 * * 6' || true; done",
#             # ]
#             [sleep 3600]
#           env:
#             - name: DRONE_TOKEN
#               valueFrom:
#                 secretKeyRef:
#                   name: drone-personal-token
#                   key: DRONE_PERSONAL_TOKEN
#                   optional: false
#             - name: DRONE_SERVER
#               value: "http://drone-server-svc.devops.svc.cluster.local:8080"
#             - name: REPOS
#               value: "shelly-init protonmail-bridge"
#       imagePullSecrets:
#         - name: harbor-registry-creds

---
kind: Job
apiVersion: batch/v1
metadata:
  name: drone-add-cron
  namespace: devops
  labels:
    app: drone-add-cron
spec:
  template:
    spec:
      containers:
        - name: drone-add-cron
          image: "harbor.k8s.lan/k8s/drone-cli:latest"
          imagePullPolicy: Always
          resources: {}
          command: ["/bin/sh", "-c"]
          args:
            [
              "IFS=,; for r in ${REPOS}; do drone cron add --branch ${DEFAULT_BRANCH} ${ORGANIZATION}/${r} schedule-from-job ${SCHEDULE} 2>&1 | grep -q UNIQUE && echo ${r} 'already added' || exit 10; done",
            ]
          env:
            - name: DRONE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: drone-personal-token
                  key: DRONE_PERSONAL_TOKEN
                  optional: false
            - name: DRONE_SERVER
              value: "http://drone-server-svc.devops.svc.cluster.local:8080"
            - name: ORGANIZATION
              value: "theautomation"
            - name: REPOS
              value: "shelly-init,protonmail-bridge" #A comma seperate list of the repos
            - name: SCHEDULE
              value: "0 1 * * 6"
            - name: DEFAULT_BRANCH
              value: "main"
      restartPolicy: Never
      imagePullSecrets:
        - name: harbor-registry-creds
  backoffLimit: 0
