---
kind: Job
apiVersion: batch/v1
metadata:
  name: drone-add-cron
  namespace: devops
  labels:
    app: drone-add-cron
spec:
  template:
    spec:
      containers:
        - name: drone-add-cron
          image: "harbor.k8s.lan/k8s/drone-cli:latest"
          imagePullPolicy: Always
          resources: {}
          command: ["/bin/sh", "-c"]
          args:
            [
              "until curl -s ${DRONE_SERVER}/healthzz | grep -q 'OK'; do echo 'Waiting for Drone server...' && sleep 2; done; for r in ${REPOS}; do drone cron add --branch main theautomation/${r} saturday '0 1 * * 6' || true; done",
            ]
          env:
            - name: DRONE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: drone-personal-token
                  key: DRONE_PERSONAL_TOKEN
                  optional: false
            - name: DRONE_SERVER
              value: "http://drone-server-svc.devops.svc.cluster.local:8080"
            - name: REPOS
              value: "shelly-init protonmail-bridge"
      restartPolicy: Never
      imagePullSecrets:
        - name: harbor-registry-creds
  backoffLimit: 4